# Generated by Django 4.2.10 on 2024-08-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_article', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(max_length=255),
        ),
    ]
