# Generated by Django 4.2.10 on 2024-08-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_article', '0006_article_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='wp_status',
            field=models.CharField(max_length=10),
        ),
    ]
