# Generated by Django 4.2.10 on 2024-08-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_article', '0007_alter_article_wp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='site_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
