# Generated by Django 4.2.10 on 2024-07-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0005_sitedata_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
