# Generated by Django 4.2.10 on 2024-07-01 08:54

from django.db import migrations, models
import sitesetting.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='email',
            field=models.EmailField(default=sitesetting.models.default_email, max_length=255),
        ),
    ]
