# Generated by Django 4.2.10 on 2024-07-15 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0004_sitedata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
