name: Deploy React-Flask Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Production Environment Variables
      run: |
      echo "REACT_APP_API_URL=${{ secrets.PRODUCTION_API_URL }}" > .env

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.LIF_ID }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@133.242.160.145 << 'EOF'
          cd ~/python/posttool
          git remote set-url origin git@github.com:lifcompany/Blitzwrite_Backend.git

          eval $(ssh-agent -s)
          ssh-add ~/.ssh/sm_automation.pem
          ssh-add -l

          git pull origin main
          
          cd ~/python/Blitzwrite_Backend
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements/local.txt
          pm2 restart server || pm2 start start.sh --name server
          pm2 save

          echo "Deployment completed."
        EOF
